apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simplecontroller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - "get"
      - "list"
      - "patch"
      - "update"
      - "watch"
